api_msg:
  port: 5000

hutch: 'xcs'
experiment: 'xcsx39718'
run: '10'

det_map:
  name: 'epix10k2M'
  shape:
    - 1667
    - 1668
  dtype: float32
  bins: 100

pv_map:
  1: 'XCS:JTRK:REQ:DIFF_INTENSITY'
  2: 'XCS:JTRK:REQ:I0'

ipm: 
  name: 'XCS-SB2-BMMON'
  det: 'TotalIntensity'
  #name: 'XCS-IPM-03'
  #det: 'sum'

jet_cam:
  name: 'opal_1'
  axis: 0

cal_params:
  azav_bins: 100
  events: 50
  i0_bins: 20  # Number of bins for i0 hist cuts
  i0_reject: 0.1  # Percent below peak pin to make cut
  fit_points: 5  # Number of points at start and end of azav array to do line fit
  delta_bin: 3  # Number of azav bins around peak used for integration
#ipm:
#  name: 'CXI-DG2-BMMON'
#  det: None
