api_msg:
  port: 5000

det_map:
  name: 'jungfrau4M'
  shape:
    - 2203
    - 2299
  dtype: float32
  bins: 100

pv_map:
  1: 'CXI:JTRK:REQ:DIFF_INTENSITY'
  2: 'CXI:JTRK:REQ:I0'

ipm: 
  name: 'FEEGasDetEnergy'
  det: 'f_12_ENRC' 

hutch: 'cxi'
#ipm:
#  name: 'CXI-DG2-BMMON'
#  det: None
